<?php
/**
 * @file
 * Code for the Sociedades feature.
 */

include_once 'sociedades.features.inc';

function sociedades_init(){
  drupal_add_js('https://www.google.com/jsapi', 'external');
  drupal_add_js(drupal_get_path('module', 'sociedades') . '/sociedades.graficos.js');
}

/**
 * Implements hook_node_view().
 */
function sociedades_node_view($node, $view_mode, $langcode) {
  dpm($node);
  if($node->type == 'sociedad'){
    dpm('hola');
    $entidad = entity_metadata_wrapper('node', $node);
    $id_mailchimp = $entidad->field_proyecto_id_mailchimp->value();
  }
}

