<?php
/**
 * @file
 * Code for the Sociedades feature.
 */

include_once 'sociedades.features.inc';

function sociedades_init(){
  drupal_add_js('https://www.google.com/jsapi', 'external');
  drupal_add_js(drupal_get_path('module', 'sociedades') . '/sociedades.graficos.js');
}

/**
 * Implements hook_node_view().
 */
function sociedades_node_view($node, $view_mode, $langcode) {
  // if($node->type == 'sociedad'){
  //   $entidad = entity_metadata_wrapper('node', $node);
  //   if(isset($entidad->field_sociedad_grafico_capital->url)){
  //     $url = $entidad->field_sociedad_grafico_capital->url->value();
  //     drupal_add_js(array('sociedad_grafico_capital' => $url), 'setting');
  //   }
  // }
}

