<?php
module_load_include('inc', 'bt_base', 'bt_base.blocks');


/**
 * @file bt_base.module
 * Modulo de utilidades
 */

/**
 * Implements hook_ctools_plugin_directory()
 */
function bt_base_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
    return "plugins/$plugin";
  }
}

function bt_base_theme() {
  return array(
    'footer' => array(
      'path' => drupal_get_path('module', 'bt_base') . '/templates',
      'template' => 'footer'
    ),
  );
}


