<?php
/**
 * @file
 * Code for the Proyectos feature.
 */

include_once 'proyectos.features.inc';


function proyectos_flag_flag($flag, $entity_id, $account, $flagging){
  if($flagging->flag_name == 'seguir_proyecto'){
    $user = user_load($account->uid);
    $nodo = node_load($entity_id);
    $entidad = entity_metadata_wrapper('node', $nodo);
    $id_mailchimp = $entidad->field_proyecto_id_mailchimp->value();
    $valor_grupo = $entidad->field_proyecto_grupo_mailchimp->value();
    $mc_list = mailchimp_get_list($id_mailchimp);

    $intgroups = $mc_list['intgroups'][0]['groups'];
    $id_grupo = $mc_list['intgroups'][0]['id'];
    $mergevars = $mc_list['mergevars'];

    foreach ($intgroups as $key => $value) {
      if($value['name'] == $valor_grupo){
        $id_valor_grupo = $value['id'];
      }
    }
    $merge_preparado = array(
      'EMAIL' => $user->mail,
      'FNAME' => $user->name,
      'GROUPINGS' => array(
        array(
          'id' => $id_grupo,
          'groups' => array(
            $valor_grupo => $valor_grupo
          )
        )
      )
    );
   $ret = mailchimp_subscribe($id_mailchimp, $user->mail, $merge_preparado, FALSE, FALSE, 'html', false, TRUE);
  }
}


function proyectos_flag_unflag($flag, $entity_id, $account, $flagging){
  dpm('unflag');
  if ($flagging == 'flag') { // Or $action == 'unflag'.
  }
}

function proyectos_suscribir_lista($id_lista, $email, $entity_id){

}
