<?php
/**
 * @file
 * home.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function home_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_emprendedores:http://bestaker.localhost:8082/es/admin/structure/menu/item/747/edit#emprendedores
  $menu_links['main-menu_emprendedores:http://bestaker.localhost:8082/es/admin/structure/menu/item/747/edit#emprendedores'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/747/edit#emprendedores',
    'router_path' => '',
    'link_title' => 'Emprendedores',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#emprendedores',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_emprendedores:http://bestaker.localhost:8082/es/admin/structure/menu/item/747/edit#emprendedores',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_entrepreneurs:http://bestaker.localhost:8082/es/admin/structure/menu/item/751/edit#emprendedores
  $menu_links['main-menu_entrepreneurs:http://bestaker.localhost:8082/es/admin/structure/menu/item/751/edit#emprendedores'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/751/edit#emprendedores',
    'router_path' => '',
    'link_title' => 'Entrepreneurs',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#emprendedores',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_entrepreneurs:http://bestaker.localhost:8082/es/admin/structure/menu/item/751/edit#emprendedores',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
  );
  // Exported menu link: main-menu_inversores:http://bestaker.localhost:8082/es/admin/structure/menu/item/746/edit#inversores
  $menu_links['main-menu_inversores:http://bestaker.localhost:8082/es/admin/structure/menu/item/746/edit#inversores'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/746/edit#inversores',
    'router_path' => '',
    'link_title' => 'Inversores',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#inversores',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_inversores:http://bestaker.localhost:8082/es/admin/structure/menu/item/746/edit#inversores',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_investors:http://bestaker.localhost:8082/es/admin/structure/menu/item/750/edit#inversores
  $menu_links['main-menu_investors:http://bestaker.localhost:8082/es/admin/structure/menu/item/750/edit#inversores'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/750/edit#inversores',
    'router_path' => '',
    'link_title' => 'Investors',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#inversores',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_investors:http://bestaker.localhost:8082/es/admin/structure/menu/item/750/edit#inversores',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_news:http://bestaker.localhost:8082/es/admin/structure/menu/item/752/edit#noticias
  $menu_links['main-menu_news:http://bestaker.localhost:8082/es/admin/structure/menu/item/752/edit#noticias'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/752/edit#noticias',
    'router_path' => '',
    'link_title' => 'News',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#noticias',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_news:http://bestaker.localhost:8082/es/admin/structure/menu/item/752/edit#noticias',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
  );
  // Exported menu link: main-menu_noticias:http://bestaker.localhost:8082/es/admin/structure/menu/item/748/edit#noticias
  $menu_links['main-menu_noticias:http://bestaker.localhost:8082/es/admin/structure/menu/item/748/edit#noticias'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/748/edit#noticias',
    'router_path' => '',
    'link_title' => 'Noticias',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#noticias',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_noticias:http://bestaker.localhost:8082/es/admin/structure/menu/item/748/edit#noticias',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_qu-hacemos:http://bestaker.localhost:8082/es/admin/structure/menu/item/745/edit#hacemos
  $menu_links['main-menu_qu-hacemos:http://bestaker.localhost:8082/es/admin/structure/menu/item/745/edit#hacemos'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/745/edit#hacemos',
    'router_path' => '',
    'link_title' => 'Qué hacemos',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#hacemos',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_qu-hacemos:http://bestaker.localhost:8082/es/admin/structure/menu/item/745/edit#hacemos',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: main-menu_what-we-do:http://bestaker.localhost:8082/es/admin/structure/menu/item/749/edit#hacemos
  $menu_links['main-menu_what-we-do:http://bestaker.localhost:8082/es/admin/structure/menu/item/749/edit#hacemos'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'http://bestaker.localhost:8082/es/admin/structure/menu/item/749/edit#hacemos',
    'router_path' => '',
    'link_title' => 'What we do',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#hacemos',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'main-menu_what-we-do:http://bestaker.localhost:8082/es/admin/structure/menu/item/749/edit#hacemos',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Emprendedores');
  t('Entrepreneurs');
  t('Inversores');
  t('Investors');
  t('News');
  t('Noticias');
  t('Qué hacemos');
  t('What we do');


  return $menu_links;
}
